defmodule Reet.Repo.Migrations.TimestampsAndUuid7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :created_at, to: :inserted_at

    alter table(:users) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end

  def down do
    alter table(:users) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :created_at, :utc_datetime_usec, default: nil
      modify :updated_at, :utc_datetime_usec, default: nil
    end

    rename table(:users), :inserted_at, to: :created_at
  end
end
