defmodule AshBaseTemplate.Repo.Migrations.AddNewsletter do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:newsletters, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
      add :confirmed, :boolean, null: false, default: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:newsletters, [:email], name: "newsletters_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:newsletters, [:email], name: "newsletters_unique_email_index")

    drop table(:newsletters)
  end
end
