defmodule AshBaseTemplate.Repo.Migrations.InstallAshMoneyV520260108160711 do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "DROP OPERATOR >=(public.money_with_currency, public.money_with_currency);"
    execute "DROP OPERATOR >=(public.money_with_currency, numeric);"

    execute """
    CREATE OPERATOR >= (
        leftarg = public.money_with_currency,
        rightarg = public.money_with_currency,
        procedure = money_gte
    );
    """

    execute """
    CREATE OPERATOR >= (
        leftarg = public.money_with_currency,
        rightarg = numeric,
        procedure = money_gte
    );
    """
  end

  def down do
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:
    execute "DROP OPERATOR >=(public.money_with_currency, public.money_with_currency);"
    execute "DROP OPERATOR >=(public.money_with_currency, numeric);"

    execute """
    CREATE OPERATOR >= (
        leftarg = public.money_with_currency,
        rightarg = public.money_with_currency,
        procedure = money_gt
    );
    """

    execute """
    CREATE OPERATOR >= (
        leftarg = money_with_currency,
        rightarg = numeric,
        procedure = money_gt
    );
    """

    execute "DROP TYPE IF EXISTS public.money_with_currency CASCADE;"
  end
end
